// Generated by CoffeeScript 1.6.2
var request;

request = (function() {
  function request() {
    this.verb = null;
    this.protocol = null;
    this.version = null;
    this.uri = null;
    this.headers = {};
  }

  request.prototype.parse = function(buffer) {};

  return request;

})();
