// Generated by CoffeeScript 1.6.2
var colors, dgram, root, server;

dgram = require('dgram');

colors = require('colors');

root = typeof exports !== "undefined" && exports !== null ? exports : this;

server = (function() {
  function server(port) {
    this.port = port || 554;
    this.address = '0.0.0.0';
  }

  server.prototype.init = function() {
    return this.socket = null;
  };

  server.prototype.start = function(socketType) {
    if (socketType !== 'udp4' && socketType !== 'udp6') {
      socketType = 'udp4';
    }
    this.socket = require('dgram').createSocket('udp4');
    this.socket.on('message', this.parseRequest.bind(this));
    this.socket.on('listening', this.listening.bind(this));
    this.socket.on('close', this.close.bind(this));
    return this.socket.bind(this.port);
  };

  server.prototype.parseRequest = function(msg, rinfo) {
    return console.log('[event][msg] - RTSP server got message ' + msg);
  };

  server.prototype.listening = function() {
    return console.log('[event][listen] - RTSP server listening on ' + server.address().address + ':' + this.port);
  };

  server.prototype.close = function() {
    return console.log('[event][close] - RTSP server close');
  };

  return server;

})();

root.server = server;

root.createServer = function(fn) {
  return new server();
};
